---
title: "Gene_biotypes"
author: "María Carazo"
date: "2025-06-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
library(readr)
library(biomaRt)
library(textshape)
```

```{r}
tpms_path <- "sRNA_gencode_GB_Control_COUNTS_AGGREGATED-lengthScaledTPM.tab"

counts <- read_delim(
  tpms_path, 
  delim = "\t", 
  escape_double = FALSE,
  trim_ws = TRUE
)

colnames(counts)
```

Extraer `gene_biotype` desde biomart
```{r}
ensembl <- useEnsembl(biomart = "genes", dataset = "hsapiens_gene_ensembl")  # humano; cambia a mouse si necesitas

biotypes <- getBM(
  attributes = c("ensembl_gene_id", "gene_biotype"),
  filters = "ensembl_gene_id",
  values = counts$GENEID,
  mart = ensembl
)
```

```{r}
counts_annot <- counts %>%
  left_join(biotypes, by = c("GENEID" = "ensembl_gene_id"))
```


```{r}
expr_cols <- colnames(counts_annot)[!(colnames(counts_annot) %in% c("GENEID", "GENENAME", "gene_biotype"))]

long_counts <- counts_annot %>%
  pivot_longer(cols = all_of(expr_cols), names_to = "sample", values_to = "count")

# Agrupar muestras por nombre
long_counts <- long_counts %>%
  mutate(group = ifelse(grepl("^GB", sample), "GBM", "Control"))

summary_grouped <- long_counts %>%
  group_by(GENEID, gene_biotype, group)  %>%
  summarise(median_count = median(count, na.rm = TRUE), .groups = "drop") #%>% filter(gene_biotype == "rRNA")

summary_grouped <- summary_grouped %>%
  group_by(gene_biotype, group) %>%
  summarise(total_count = sum(median_count, na.rm = TRUE), .groups = "drop") #%>% filter(gene_biotype != "rRNA")

q3_per_group <- summary_grouped %>%
  group_by(group) %>%
  summarise(Q3 = quantile(total_count, 0.75), .groups = "drop")

top_quartile_biotypes <- summary_grouped %>%
  left_join(q3_per_group, by = "group") %>%
  filter(total_count >= Q3) %>% drop_na(gene_biotype)
```

```{r}
ggplot(top_quartile_biotypes, aes(x = gene_biotype, y = total_count, fill = group)) +
  geom_col(position = "dodge") +
  labs(title = "Top gene biotypes",
       x = "Gene biotype",
       y = "Fraction counts") +
  theme_minimal() +
  scale_fill_manual(values = c("GBM" = "mediumpurple", "Control" = "orange")) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size=12))
```

